<?php namespace Srw\Azimut;

use System\Classes\PluginBase;
use Response;

class Plugin extends PluginBase
{
    public function registerComponents()
    {
    }

    public function registerSettings()
    {
    }

    public array $links = [
        'morskie-kruizy',
        'tury-po-evrope',
        'morskie-kruizy/kruizy-po-chernomu-moryu',
        'kruizy-na-parome-iz-peterburga',
        'kruizy-na-parome-iz-peterburga/kruizy-v-norvezhskie-fordy',
        'kruizy-na-parome-iz-peterburga/parom-romantika',
        'kruizy-na-parome-iz-peterburga/parom-silja-serenade',
        'kruizy-na-parome-iz-peterburga/parom-baltic-queen',
        'kruizy-na-parome-iz-peterburga/parom-galaxy',
        'kruizy-na-parome-iz-peterburga/parom-mariella',
        'kruizy-na-parome-iz-peterburga/parom-victoria-1',
        'kruizy-na-parome-iz-peterburga/parom-silja-symphony',
        'kruizy-na-parome-iz-peterburga/parom-princess-anastasia',
        'kruizy-na-parome-iz-peterburga/kruizy-v-pribaltiku',
        'kruizy-na-parome-iz-peterburga/parom-isabelle',
        'kruizy-na-parome-iz-peterburga/kruizy-na-parome-anastasia',
        'kruizy-na-parome-iz-peterburga/kruizy-v-stokgolm-tallin-rigu',
        'kruizy-na-parome-iz-peterburga/tury-po-evrope-avtobus-parom',
        'kruizy-na-parome-iz-peterburga/parom-baltic-princess',
        'kruizy-na-parome-iz-peterburga/parom-gabriella',
        'kruizy-na-parome-iz-peterburga/kruizy-v-finlyandiyu',
        'kruizy-na-parome-iz-peterburga/parom-viking-xprs',
    ];

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        $url = request()->path();
        if (in_array($url, $this->links)) {
            Response::make(\View::make('cms::404'), 404)->send();
            exit();
        }
    }
}
